version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "16:00"
      timezone: "Asia/Seoul"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      spring:
        patterns: ["org.springframework*"]
        update-types: ["minor", "patch"]
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "16:00"
      timezone: "Asia/Seoul"
    commit-message:
      prefix: "chore(deps)"
    groups:
      actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]
